# Copyright 2015 VMware, Inc.  All rights reserved.
# SPDX-License-Identifier: MIT OR GPL-3.0-only
---
- name: Reload systemd
  become: yes
  command: systemctl --system daemon-reload

- name: Reload systemd-timesyncd
  become: yes
  command: systemctl restart systemd-timesyncd

- name: Enable ntp
  become: yes
  command: timedatectl set-ntp true
  notify: Reload systemd-timesyncd

- name: Reload logrotate.timer
  become: yes
  command: systemctl restart logrotate.timer

- name: Stop logrotate.timer
  become: yes
  command: systemctl stop logrotate.timer

- name: Run logrotate
  become: yes
  command: /usr/sbin/logrotate -fv /etc/logrotate.d/docker-container-logrotate
