#!/bin/bash

VERSION=$(docker --version | awk '{print $3}' | sed 's/,//')
BASE_DIR="/opt/bin"
BINARY="$BASE_DIR/docker-$VERSION-static"
LINK="$BASE_DIR/docker.static"

if [ ! -e "$BINARY" ]; then
    mkdir -p "$BASE_DIR/docker-$VERSION"
    curl -fsSLO "https://get.docker.com/builds/Linux/x86_64/docker-$VERSION.tgz" && tar --strip-components=1 -xvzf "docker-$VERSION.tgz" -C "$BASE_DIR/docker-$VERSION"
    mv "$BASE_DIR/docker-$VERSION/docker" "$BINARY"
    chmod a+x "$BINARY"
    ln -sf "$BINARY" "$LINK"
    rm -r "$BASE_DIR/docker-$VERSION"
fi
